### Import Dependancies

In [1]:
import pandas as pd
import numpy as np
import seaborn as sns
import matplotlib.pyplot as plt
import plotly.express as px
import warnings
from nltk.stem import PorterStemmer
from sklearn.feature_extraction.text import TfidfVectorizer
import ast
warnings.filterwarnings('ignore')

### Reading Dataset

In [2]:
credits=pd.read_csv("tmdb_5000_credits.csv")
movies=pd.read_csv("tmdb_5000_movies.csv")

In [3]:
credits.head()

,movie_id,title,cast,crew
0,19995,Avatar,"[{""cast_id"": 242, ""character"": ""Jake Sully"", ""...","[{""credit_id"": ""52fe48009251416c750aca23"", ""de..."
1,285,Pirates of the Caribbean: At World's End,"[{""cast_id"": 4, ""character"": ""Captain Jack Spa...","[{""credit_id"": ""52fe4232c3a36847f800b579"", ""de..."
2,206647,Spectre,"[{""cast_id"": 1, ""character"": ""James Bond"", ""cr...","[{""credit_id"": ""54805967c3a36829b5002c41"", ""de..."
3,49026,The Dark Knight Rises,"[{""cast_id"": 2, ""character"": ""Bruce Wayne / Ba...","[{""credit_id"": ""52fe4781c3a36847f81398c3"", ""de..."
4,49529,John Carter,"[{""cast_id"": 5, ""character"": ""John Carter"", ""c...","[{""credit_id"": ""52fe479ac3a36847f813eaa3"", ""de..."

In [4]:
credits.shape

(4803, 4)

In [5]:
movies.head()

,budget,genres,homepage,id,keywords,original_language,original_title,overview,popularity,production_companies,production_countries,release_date,revenue,runtime,spoken_languages,status,tagline,title,vote_average,vote_count
0,237000000,"[{""id"": 28, ""name"": ""Action""}, {""id"": 12, ""nam...",http://www.avatarmovie.com/,19995,"[{""id"": 1463, ""name"": ""culture clash""}, {""id"":...",en,Avatar,"In the 22nd century, a paraplegic Marine is di...",150.437577,"[{""name"": ""Ingenious Film Partners"", ""id"": 289...","[{""iso_3166_1"": ""US"", ""name"": ""United States o...",2009-12-10,2787965087,162.0,"[{""iso_639_1"": ""en"", ""name"": ""English""}, {""iso...",Released,Enter the World of Pandora.,Avatar,7.2,11800
1,300000000,"[{""id"": 12, ""name"": ""Adventure""}, {""id"": 14, ""...",http://disney.go.com/disneypictures/pirates/,285,"[{""id"": 270, ""name"": ""ocean""}, {""id"": 726, ""na...",en,Pirates of the Caribbean: At World's End,"Captain Barbossa, long believed to be dead, ha...",139.082615,"[{""name"": ""Walt Disney Pictures"", ""id"": 2}, {""...","[{""iso_3166_1"": ""US"", ""name"": ""United States o...",2007-05-19,961000000,169.0,"[{""iso_639_1"": ""en"", ""name"": ""English""}]",Released,"At the end of the world, the adventure begins.",Pirates of the Caribbean: At World's End,6.9,4500
2,245000000,"[{""id"": 28, ""name"": ""Action""}, {""id"": 12, ""nam...",http://www.sonypictures.com/movies/spectre/,206647,"[{""id"": 470, ""name"": ""spy""}, {""id"": 818, ""name...",en,Spectre,A cryptic message from Bondâ€™s past sends him o...,107.376788,"[{""name"": ""Columbia Pictures"", ""id"": 5}, {""nam...","[{""iso_3166_1"": ""GB"", ""name"": ""United Kingdom""...",2015-10-26,880674609,148.0,"[{""iso_639_1"": ""fr"", ""name"": ""Fran\u00e7ais""},...",Released,A Plan No One Escapes,Spectre,6.3,4466
3,250000000,"[{""id"": 28, ""name"": ""Action""}, {""id"": 80, ""nam...",http://www.thedarkknightrises.com/,49026,"[{""id"": 849, ""name"": ""dc comics""}, {""id"": 853,...",en,The Dark Knight Rises,Following the death of District Attorney Harve...,112.312950,"[{""name"": ""Legendary Pictures"", ""id"": 923}, {""...","[{""iso_3166_1"": ""US"", ""name"": ""United States o...",2012-07-16,1084939099,165.0,"[{""iso_639_1"": ""en"", ""name"": ""English""}]",Released,The Legend Ends,The Dark Knight Rises,7.6,9106
4,260000000,"[{""id"": 28, ""name"": ""Action""}, {""id"": 12, ""nam...",http://movies.disney.com/john-carter,49529,"[{""id"": 818, ""name"": ""based on novel""}, {""id"":...",en,John Carter,"John Carter is a war-weary, former military ca...",43.926995,"[{""name"": ""Walt Disney Pictures"", ""id"": 2}]","[{""iso_3166_1"": ""US"", ""name"": ""United States o...",2012-03-07,284139100,132.0,"[{""iso_639_1"": ""en"", ""name"": ""English""}]",Released,"Lost in our world, found in another.",John Carter,6.1,2124

In [6]:
movies.shape

(4803, 20)

### Mergeing dataset

In [7]:
df=pd.merge(movies,credits,how='inner',left_on=movies['id'],right_on=credits['movie_id'])

In [8]:
print(df.shape)
df.head()

(4803, 25)

,key_0,budget,genres,homepage,id,keywords,original_language,original_title,overview,popularity,...,spoken_languages,status,tagline,title_x,vote_average,vote_count,movie_id,title_y,cast,crew
0,19995,237000000,"[{""id"": 28, ""name"": ""Action""}, {""id"": 12, ""nam...",http://www.avatarmovie.com/,19995,"[{""id"": 1463, ""name"": ""culture clash""}, {""id"":...",en,Avatar,"In the 22nd century, a paraplegic Marine is di...",150.437577,...,"[{""iso_639_1"": ""en"", ""name"": ""English""}, {""iso...",Released,Enter the World of Pandora.,Avatar,7.2,11800,19995,Avatar,"[{""cast_id"": 242, ""character"": ""Jake Sully"", ""...","[{""credit_id"": ""52fe48009251416c750aca23"", ""de..."
1,285,300000000,"[{""id"": 12, ""name"": ""Adventure""}, {""id"": 14, ""...",http://disney.go.com/disneypictures/pirates/,285,"[{""id"": 270, ""name"": ""ocean""}, {""id"": 726, ""na...",en,Pirates of the Caribbean: At World's End,"Captain Barbossa, long believed to be dead, ha...",139.082615,...,"[{""iso_639_1"": ""en"", ""name"": ""English""}]",Released,"At the end of the world, the adventure begins.",Pirates of the Caribbean: At World's End,6.9,4500,285,Pirates of the Caribbean: At World's End,"[{""cast_id"": 4, ""character"": ""Captain Jack Spa...","[{""credit_id"": ""52fe4232c3a36847f800b579"", ""de..."
2,206647,245000000,"[{""id"": 28, ""name"": ""Action""}, {""id"": 12, ""nam...",http://www.sonypictures.com/movies/spectre/,206647,"[{""id"": 470, ""name"": ""spy""}, {""id"": 818, ""name...",en,Spectre,A cryptic message from Bondâ€™s past sends him o...,107.376788,...,"[{""iso_639_1"": ""fr"", ""name"": ""Fran\u00e7ais""},...",Released,A Plan No One Escapes,Spectre,6.3,4466,206647,Spectre,"[{""cast_id"": 1, ""character"": ""James Bond"", ""cr...","[{""credit_id"": ""54805967c3a36829b5002c41"", ""de..."
3,49026,250000000,"[{""id"": 28, ""name"": ""Action""}, {""id"": 80, ""nam...",http://www.thedarkknightrises.com/,49026,"[{""id"": 849, ""name"": ""dc comics""}, {""id"": 853,...",en,The Dark Knight Rises,Following the death of District Attorney Harve...,112.312950,...,"[{""iso_639_1"": ""en"", ""name"": ""English""}]",Released,The Legend Ends,The Dark Knight Rises,7.6,9106,49026,The Dark Knight Rises,"[{""cast_id"": 2, ""character"": ""Bruce Wayne / Ba...","[{""credit_id"": ""52fe4781c3a36847f81398c3"", ""de..."
4,49529,260000000,"[{""id"": 28, ""name"": ""Action""}, {""id"": 12, ""nam...",http://movies.disney.com/john-carter,49529,"[{""id"": 818, ""name"": ""based on novel""}, {""id"":...",en,John Carter,"John Carter is a war-weary, former military ca...",43.926995,...,"[{""iso_639_1"": ""en"", ""name"": ""English""}]",Released,"Lost in our world, found in another.",John Carter,6.1,2124,49529,John Carter,"[{""cast_id"": 5, ""character"": ""John Carter"", ""c...","[{""credit_id"": ""52fe479ac3a36847f813eaa3"", ""de..."

In [9]:
df.columns

Index(['key_0', 'budget', 'genres', 'homepage', 'id', 'keywords',
       'original_language', 'original_title', 'overview', 'popularity',
       'production_companies', 'production_countries', 'release_date',
       'revenue', 'runtime', 'spoken_languages', 'status', 'tagline',
       'title_x', 'vote_average', 'vote_count', 'movie_id', 'title_y', 'cast',
       'crew'],
      dtype='object')

In [10]:
df=df[['id','original_title','original_language','overview','genres', 'keywords','cast','crew']]

In [11]:
df

,id,original_title,original_language,overview,genres,keywords,cast,crew
0,19995,Avatar,en,"In the 22nd century, a paraplegic Marine is di...","[{""id"": 28, ""name"": ""Action""}, {""id"": 12, ""nam...","[{""id"": 1463, ""name"": ""culture clash""}, {""id"":...","[{""cast_id"": 242, ""character"": ""Jake Sully"", ""...","[{""credit_id"": ""52fe48009251416c750aca23"", ""de..."
1,285,Pirates of the Caribbean: At World's End,en,"Captain Barbossa, long believed to be dead, ha...","[{""id"": 12, ""name"": ""Adventure""}, {""id"": 14, ""...","[{""id"": 270, ""name"": ""ocean""}, {""id"": 726, ""na...","[{""cast_id"": 4, ""character"": ""Captain Jack Spa...","[{""credit_id"": ""52fe4232c3a36847f800b579"", ""de..."
2,206647,Spectre,en,A cryptic message from Bondâ€™s past sends him o...,"[{""id"": 28, ""name"": ""Action""}, {""id"": 12, ""nam...","[{""id"": 470, ""name"": ""spy""}, {""id"": 818, ""name...","[{""cast_id"": 1, ""character"": ""James Bond"", ""cr...","[{""credit_id"": ""54805967c3a36829b5002c41"", ""de..."
3,49026,The Dark Knight Rises,en,Following the death of District Attorney Harve...,"[{""id"": 28, ""name"": ""Action""}, {""id"": 80, ""nam...","[{""id"": 849, ""name"": ""dc comics""}, {""id"": 853,...","[{""cast_id"": 2, ""character"": ""Bruce Wayne / Ba...","[{""credit_id"": ""52fe4781c3a36847f81398c3"", ""de..."
4,49529,John Carter,en,"John Carter is a war-weary, former military ca...","[{""id"": 28, ""name"": ""Action""}, {""id"": 12, ""nam...","[{""id"": 818, ""name"": ""based on novel""}, {""id"":...","[{""cast_id"": 5, ""character"": ""John Carter"", ""c...","[{""credit_id"": ""52fe479ac3a36847f813eaa3"", ""de..."
...,...,...,...,...,...,...,...,...
4798,9367,El Mariachi,es,El Mariachi just wants to play his guitar and ...,"[{""id"": 28, ""name"": ""Action""}, {""id"": 80, ""nam...","[{""id"": 5616, ""name"": ""united states\u2013mexi...","[{""cast_id"": 1, ""character"": ""El Mariachi"", ""c...","[{""credit_id"": ""52fe44eec3a36847f80b280b"", ""de..."
4799,72766,Newlyweds,en,A newlywed couple's honeymoon is upended by th...,"[{""id"": 35, ""name"": ""Comedy""}, {""id"": 10749, ""...",[],"[{""cast_id"": 1, ""character"": ""Buzzy"", ""credit_...","[{""credit_id"": ""52fe487dc3a368484e0fb013"", ""de..."
4800,231617,"Signed, Sealed, Delivered",en,"""Signed, Sealed, Delivered"" introduces a dedic...","[{""id"": 35, ""name"": ""Comedy""}, {""id"": 18, ""nam...","[{""id"": 248, ""name"": ""date""}, {""id"": 699, ""nam...","[{""cast_id"": 8, ""character"": ""Oliver O\u2019To...","[{""credit_id"": ""52fe4df3c3a36847f8275ecf"", ""de..."
4801,126186,Shanghai Calling,en,When ambitious New York attorney Sam is sent t...,[],[],"[{""cast_id"": 3, ""character"": ""Sam"", ""credit_id...","[{""credit_id"": ""52fe4ad9c3a368484e16a36b"", ""de..."
4802,25975,My Date with Drew,en,Ever since the second grade when he first saw ...,"[{""id"": 99, ""name"": ""Documentary""}]","[{""id"": 1523, ""name"": ""obsession""}, {""id"": 224...","[{""cast_id"": 3, ""character"": ""Herself"", ""credi...","[{""credit_id"": ""58ce021b9251415a390165d9"", ""de..."

### Checking Null Values and Droping Non useable Columns

In [12]:
df.isna().sum()

id                   0
original_title       0
original_language    0
overview             3
genres               0
keywords             0
cast                 0
crew                 0
dtype: int64

In [13]:
df.dropna(inplace=True)

In [14]:
df

,id,original_title,original_language,overview,genres,keywords,cast,crew
0,19995,Avatar,en,"In the 22nd century, a paraplegic Marine is di...","[{""id"": 28, ""name"": ""Action""}, {""id"": 12, ""nam...","[{""id"": 1463, ""name"": ""culture clash""}, {""id"":...","[{""cast_id"": 242, ""character"": ""Jake Sully"", ""...","[{""credit_id"": ""52fe48009251416c750aca23"", ""de..."
1,285,Pirates of the Caribbean: At World's End,en,"Captain Barbossa, long believed to be dead, ha...","[{""id"": 12, ""name"": ""Adventure""}, {""id"": 14, ""...","[{""id"": 270, ""name"": ""ocean""}, {""id"": 726, ""na...","[{""cast_id"": 4, ""character"": ""Captain Jack Spa...","[{""credit_id"": ""52fe4232c3a36847f800b579"", ""de..."
2,206647,Spectre,en,A cryptic message from Bondâ€™s past sends him o...,"[{""id"": 28, ""name"": ""Action""}, {""id"": 12, ""nam...","[{""id"": 470, ""name"": ""spy""}, {""id"": 818, ""name...","[{""cast_id"": 1, ""character"": ""James Bond"", ""cr...","[{""credit_id"": ""54805967c3a36829b5002c41"", ""de..."
3,49026,The Dark Knight Rises,en,Following the death of District Attorney Harve...,"[{""id"": 28, ""name"": ""Action""}, {""id"": 80, ""nam...","[{""id"": 849, ""name"": ""dc comics""}, {""id"": 853,...","[{""cast_id"": 2, ""character"": ""Bruce Wayne / Ba...","[{""credit_id"": ""52fe4781c3a36847f81398c3"", ""de..."
4,49529,John Carter,en,"John Carter is a war-weary, former military ca...","[{""id"": 28, ""name"": ""Action""}, {""id"": 12, ""nam...","[{""id"": 818, ""name"": ""based on novel""}, {""id"":...","[{""cast_id"": 5, ""character"": ""John Carter"", ""c...","[{""credit_id"": ""52fe479ac3a36847f813eaa3"", ""de..."
...,...,...,...,...,...,...,...,...
4798,9367,El Mariachi,es,El Mariachi just wants to play his guitar and ...,"[{""id"": 28, ""name"": ""Action""}, {""id"": 80, ""nam...","[{""id"": 5616, ""name"": ""united states\u2013mexi...","[{""cast_id"": 1, ""character"": ""El Mariachi"", ""c...","[{""credit_id"": ""52fe44eec3a36847f80b280b"", ""de..."
4799,72766,Newlyweds,en,A newlywed couple's honeymoon is upended by th...,"[{""id"": 35, ""name"": ""Comedy""}, {""id"": 10749, ""...",[],"[{""cast_id"": 1, ""character"": ""Buzzy"", ""credit_...","[{""credit_id"": ""52fe487dc3a368484e0fb013"", ""de..."
4800,231617,"Signed, Sealed, Delivered",en,"""Signed, Sealed, Delivered"" introduces a dedic...","[{""id"": 35, ""name"": ""Comedy""}, {""id"": 18, ""nam...","[{""id"": 248, ""name"": ""date""}, {""id"": 699, ""nam...","[{""cast_id"": 8, ""character"": ""Oliver O\u2019To...","[{""credit_id"": ""52fe4df3c3a36847f8275ecf"", ""de..."
4801,126186,Shanghai Calling,en,When ambitious New York attorney Sam is sent t...,[],[],"[{""cast_id"": 3, ""character"": ""Sam"", ""credit_id...","[{""credit_id"": ""52fe4ad9c3a368484e16a36b"", ""de..."
4802,25975,My Date with Drew,en,Ever since the second grade when he first saw ...,"[{""id"": 99, ""name"": ""Documentary""}]","[{""id"": 1523, ""name"": ""obsession""}, {""id"": 224...","[{""cast_id"": 3, ""character"": ""Herself"", ""credi...","[{""credit_id"": ""58ce021b9251415a390165d9"", ""de..."

In [15]:
df['genres'][0]

'[{"id": 28, "name": "Action"}, {"id": 12, "name": "Adventure"}, {"id": 14, "name": "Fantasy"}, {"id": 878, "name": "Science Fiction"}]'

In [16]:
def conver(obj):
    l=[]
    for i in ast.literal_eval(obj):
        l.append(i['name'])
    return l

In [17]:
df['genres']=df['genres'].apply(conver)

In [18]:
df['keywords']=df['keywords'].apply(conver)

In [19]:
def conver_cst(obj):
    l=[]
    counter=0
    for i in ast.literal_eval(obj):
        if counter!=3:
            l.append(i['name'])
            counter+=1
        else:
            break
    return l

In [20]:
df['cast']=df['cast'].apply(conver_cst)

In [21]:
df.head()

,id,original_title,original_language,overview,genres,keywords,cast,crew
0,19995,Avatar,en,"In the 22nd century, a paraplegic Marine is di...","[Action, Adventure, Fantasy, Science Fiction]","[culture clash, future, space war, space colon...","[Sam Worthington, Zoe Saldana, Sigourney Weaver]","[{""credit_id"": ""52fe48009251416c750aca23"", ""de..."
1,285,Pirates of the Caribbean: At World's End,en,"Captain Barbossa, long believed to be dead, ha...","[Adventure, Fantasy, Action]","[ocean, drug abuse, exotic island, east india ...","[Johnny Depp, Orlando Bloom, Keira Knightley]","[{""credit_id"": ""52fe4232c3a36847f800b579"", ""de..."
2,206647,Spectre,en,A cryptic message from Bondâ€™s past sends him o...,"[Action, Adventure, Crime]","[spy, based on novel, secret agent, sequel, mi...","[Daniel Craig, Christoph Waltz, LÃ©a Seydoux]","[{""credit_id"": ""54805967c3a36829b5002c41"", ""de..."
3,49026,The Dark Knight Rises,en,Following the death of District Attorney Harve...,"[Action, Crime, Drama, Thriller]","[dc comics, crime fighter, terrorist, secret i...","[Christian Bale, Michael Caine, Gary Oldman]","[{""credit_id"": ""52fe4781c3a36847f81398c3"", ""de..."
4,49529,John Carter,en,"John Carter is a war-weary, former military ca...","[Action, Adventure, Science Fiction]","[based on novel, mars, medallion, space travel...","[Taylor Kitsch, Lynn Collins, Samantha Morton]","[{""credit_id"": ""52fe479ac3a36847f813eaa3"", ""de..."

In [22]:
def conver_crw(obj):
    l=[]
    counter=0
    for i in ast.literal_eval(obj):
        if i['job']=='Director':
            l.append(i['name'])
            break
    return l

In [23]:
df['crew']=df['crew'].apply(conver_crw)

In [24]:
df['overview']=df['overview'].apply(lambda x:x.split())

In [25]:
df.head()

,id,original_title,original_language,overview,genres,keywords,cast,crew
0,19995,Avatar,en,"[In, the, 22nd, century,, a, paraplegic, Marin...","[Action, Adventure, Fantasy, Science Fiction]","[culture clash, future, space war, space colon...","[Sam Worthington, Zoe Saldana, Sigourney Weaver]",[James Cameron]
1,285,Pirates of the Caribbean: At World's End,en,"[Captain, Barbossa,, long, believed, to, be, d...","[Adventure, Fantasy, Action]","[ocean, drug abuse, exotic island, east india ...","[Johnny Depp, Orlando Bloom, Keira Knightley]",[Gore Verbinski]
2,206647,Spectre,en,"[A, cryptic, message, from, Bondâ€™s, past, send...","[Action, Adventure, Crime]","[spy, based on novel, secret agent, sequel, mi...","[Daniel Craig, Christoph Waltz, LÃ©a Seydoux]",[Sam Mendes]
3,49026,The Dark Knight Rises,en,"[Following, the, death, of, District, Attorney...","[Action, Crime, Drama, Thriller]","[dc comics, crime fighter, terrorist, secret i...","[Christian Bale, Michael Caine, Gary Oldman]",[Christopher Nolan]
4,49529,John Carter,en,"[John, Carter, is, a, war-weary,, former, mili...","[Action, Adventure, Science Fiction]","[based on novel, mars, medallion, space travel...","[Taylor Kitsch, Lynn Collins, Samantha Morton]",[Andrew Stanton]

In [26]:
df['cast']=df['cast'].apply(lambda x:[i.replace(" ","") for i in x])

In [27]:
df['crew']=df['crew'].apply(lambda x:[i.replace(" ","") for i in x])
df['keywords']=df['keywords'].apply(lambda x:[i.replace(" ","") for i in x])

In [28]:
df['original_language']=df['original_language'].apply(lambda x:[x])

In [29]:
df['genres']=df['genres'].apply(lambda x:[i.replace(" ","") for i in x])
df.head()

,id,original_title,original_language,overview,genres,keywords,cast,crew
0,19995,Avatar,[en],"[In, the, 22nd, century,, a, paraplegic, Marin...","[Action, Adventure, Fantasy, ScienceFiction]","[cultureclash, future, spacewar, spacecolony, ...","[SamWorthington, ZoeSaldana, SigourneyWeaver]",[JamesCameron]
1,285,Pirates of the Caribbean: At World's End,[en],"[Captain, Barbossa,, long, believed, to, be, d...","[Adventure, Fantasy, Action]","[ocean, drugabuse, exoticisland, eastindiatrad...","[JohnnyDepp, OrlandoBloom, KeiraKnightley]",[GoreVerbinski]
2,206647,Spectre,[en],"[A, cryptic, message, from, Bondâ€™s, past, send...","[Action, Adventure, Crime]","[spy, basedonnovel, secretagent, sequel, mi6, ...","[DanielCraig, ChristophWaltz, LÃ©aSeydoux]",[SamMendes]
3,49026,The Dark Knight Rises,[en],"[Following, the, death, of, District, Attorney...","[Action, Crime, Drama, Thriller]","[dccomics, crimefighter, terrorist, secretiden...","[ChristianBale, MichaelCaine, GaryOldman]",[ChristopherNolan]
4,49529,John Carter,[en],"[John, Carter, is, a, war-weary,, former, mili...","[Action, Adventure, ScienceFiction]","[basedonnovel, mars, medallion, spacetravel, p...","[TaylorKitsch, LynnCollins, SamanthaMorton]",[AndrewStanton]

In [30]:
df['tags']=(df['original_language']+df['overview']+df['genres']+df['keywords']+df['cast']+df['crew'])

In [31]:
new_df=df[['id','original_title','tags']]
new_df.head()

,id,original_title,tags
0,19995,Avatar,"[en, In, the, 22nd, century,, a, paraplegic, M..."
1,285,Pirates of the Caribbean: At World's End,"[en, Captain, Barbossa,, long, believed, to, b..."
2,206647,Spectre,"[en, A, cryptic, message, from, Bondâ€™s, past, ..."
3,49026,The Dark Knight Rises,"[en, Following, the, death, of, District, Atto..."
4,49529,John Carter,"[en, John, Carter, is, a, war-weary,, former, ..."

In [32]:
new_df['tags']=new_df['tags'].apply(lambda x:" ".join(x))

In [33]:
new_df['tags']=new_df['tags'].apply(lambda x:x.lower())

In [34]:
new_df.to_csv('movies.csv')

In [35]:
ps=PorterStemmer()

In [36]:
def stem(text):
    y=[]
    for i in text.split():
        ps.stem(i)
    string=" ".join(i)
    y.append(string)
    return y

In [37]:
def stem(text):
    y=[]
    for i in text.split():
        y.append( ps.stem(i))
        
    return " ".join(y)

In [38]:
new_df['tags']=new_df['tags'].apply(stem)

In [39]:
tfidf=TfidfVectorizer(ngram_range=(1,3),max_features=5000,stop_words='english')

In [40]:
vctrs=tfidf.fit_transform(new_df['tags']).toarray()

In [41]:
vctrs

array([[0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       ...,
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.]])

In [42]:
tfidf.get_feature_names()

['000',
 '007',
 '10',
 '10 year',
 '10 year old',
 '100',
 '11',
 '11 year',
 '11 year old',
 '12',
 '12 year',
 '12 year old',
 '13',
 '14',
 '14 year',
 '14 year old',
 '15',
 '15 year',
 '15 year old',
 '16',
 '16 year',
 '16 year old',
 '17',
 '17 year',
 '17 year old',
 '18',
 '18 year',
 '18th',
 '19',
 '19 year',
 '1910',
 '1930',
 '1940',
 '1950',
 '1960',
 '1960s',
 '1970',
 '1970s',
 '1980',
 '1990',
 '19th',
 '19th centuri',
 '19thcenturi',
 '20',
 '20 year',
 '200',
 '2009',
 '20th',
 '20th century',
 '24',
 '25',
 '30',
 '30 year',
 '3d',
 '40',
 '50',
 '500',
 '60',
 '70',
 'aaron',
 'aaroneckhart',
 'abandon',
 'abduct',
 'abigailbreslin',
 'abil',
 'abl',
 'aboard',
 'abov',
 'abus',
 'academi',
 'accept',
 'access',
 'accid',
 'accident',
 'accompani',
 'accomplish',
 'account',
 'accus',
 'ace',
 'achiev',
 'act',
 'action',
 'action adventur',
 'action adventur anim',
 'action adventur comedi',
 'action adventur crime',
 'action adventur drama',
 'action adventur fantasi',
 'action adventur sciencefict',
 'action adventur thriller',
 'action comedi',
 'action comedi crime',
 'action comedi drama',
 'action comedi famili',
 'action comedi sciencefict',
 'action comedi thriller',
 'action crime',
 'action crime drama',
 'action crime thriller',
 'action drama',
 'action drama histori',
 'action drama thriller',
 'action fantasi',
 'action histori',
 'action histori war',
 'action horror',
 'action pack',
 'action romanc',
 'action sciencefict',
 'action sciencefict adventur',
 'action sciencefict thriller',
 'action thriller',
 'action thriller adventur',
 'action thriller crime',
 'action thriller sciencefict',
 'action western',
 'actionhero',
 'activ',
 'activist',
 'activities',
 'actor',
 'actress',
 'actual',
 'adam',
 'adamsandl',
 'adamshankman',
 'adapt',
 'add',
 'addict',
 'adjust',
 'admir',
 'admit',
 'adolesc',
 'adopt',
 'ador',
 'adrienbrodi',
 'adult',
 'adulteri',
 'adulthood',
 'advanc',
 'adventur',
 'adventur action',
 'adventur action comedi',
 'adventur action sciencefict',
 'adventur action thriller',
 'adventur anim',
 'adventur anim comedi',
 'adventur anim famili',
 'adventur comedi',
 'adventur comedi crime',
 'adventur comedi drama',
 'adventur comedi famili',
 'adventur comedi sciencefict',
 'adventur crime',
 'adventur crime drama',
 'adventur drama',
 'adventur drama action',
 'adventur drama famili',
 'adventur drama histori',
 'adventur drama romanc',
 'adventur drama thriller',
 'adventur famili',
 'adventur famili fantasi',
 'adventur fantasi',
 'adventur fantasi action',
 'adventur fantasi sciencefict',
 'adventur horror',
 'adventur mysteri',
 'adventur sciencefict',
 'adventur sciencefict thriller',
 'adventur thriller',
 'adventure',
 'advertis',
 'advic',
 'advis',
 'affair',
 'affect',
 'afghanistan',
 'africa',
 'african',
 'african american',
 'africanamerican',
 'aftercreditssting',
 'aftercreditssting duringcreditssting',
 'afterlif',
 'aftermath',
 'ag',
 'age',
 'agediffer',
 'agency',
 'agenda',
 'agent',
 'agents',
 'aggress',
 'ago',
 'agre',
 'ahead',
 'aid',
 'ail',
 'aim',
 'air',
 'airplan',
 'airplanecrash',
 'airport',
 'aka',
 'al',
 'alabama',
 'alan',
 'alaska',
 'albert',
 'alcohol',
 'alcohol sex',
 'alecbaldwin',
 'alex',
 'alfredhitchcock',
 'ali',
 'alic',
 'alice',
 'alien',
 'alieninvas',
 'alienlife',
 'alienlife form',
 'alik',
 'aliv',
 'alive',
 'allen',
 'alli',
 'allianc',
 'allow',
 'alon',
 'alongsid',
 'alpacino',
 'alreadi',
 'alter',
 'alter ego',
 'altern',
 'alway',
 'alzheimer',
 'amanda',
 'amandapeet',
 'amandaseyfri',
 'amateur',
 'amaz',
 'ambassador',
 'ambit',
 'ambiti',
 'ambul',
 'ambush',
 'america',
 'american',
 'americanabroad',
 'americanfootbal',
 'amid',
 'amidst',
 'amnesia',
 'amp',
 'amus',
 'amusementpark',
 'amyadam',
 'amysmart',
 'analyst',
 'anarchiccomedi',
 'ancient',
 'ancientrom',
 'ancientworld',
 'anderson',
 'andi',
 'andiemacdowel',
 'andrew',
 'android',
 'andy',
 'andygarcÃ­a',
 'angel',
 'angelabassett',
 'angeles',
 'angelinajoli',
 'anger',
 'angle',
 'angri',
 'ani',
 'anim',
 'anim action',
 'anim adventur',
 'anim adventur comedi',
 'anim adventur famili',
 'anim comedi',
 'anim comedi famili',
 'anim drama',
 'anim famili',
 'anim famili comedi',
 'anim sciencefict',
 'animalattack',
 'animalhorror',
 'animals',
 'ann',
 'anna',
 'annafari',
 'annehathaway',
 'annemoss',
 'annetteben',
 'anni',
 'annie',
 'announc',
 'annual',
 'anonym',
 'anoth',
 'anoth man',
 'answer',
 'ant',
 'antholog',
 'anthoni',
 'anthonyanderson',
 'anthonyhopkin',
 'anthropomorph',
 'anti',
 'antihero',
 'antoniobandera',
 'antonyelchin',
 'anyon',
 'anyth',
 'apart',
 'apartheid',
 'apartment',
 'ape',
 'apocalyps',
 'apocalypt',
 'apocalypt dystopia',
 'appar',
 'appear',
 'appl',
 'appoint',
 'appreci',
 'apprentic',
 'approach',
 'april',
 'arab',
 'arch',
 'archaeologist',
 'architect',
 'arctic',
 'area',
 'aren',
 'arena',
 'argument',
 'aris',
 'aristocrat',
 'arm',
 'armi',
 'armor',
 'armsdeal',
 'army',
 'arnold',
 'arnoldschwarzenegg',
 'arrang',
 'arrest',
 'arriv',
 'arrog',
 'art',
 'arthur',
 'artificialintellig',
 'artist',
 'ash',
 'ashley',
 'ashleyjudd',
 'ashtonkutch',
 'asia',
 'ask',
 'aspir',
 'assassin',
 'assault',
 'assign',
 'assist',
 'assistant',
 'associ',
 'assum',
 'asteroid',
 'astronaut',
 'asylum',
 'athlet',
 'atomicbomb',
 'attack',
 'attempt',
 'attend',
 'attent',
 'attitud',
 'attorney',
 'attract',
 'audienc',
 'audit',
 'august',
 'aunt',
 'austin',
 'australia',
 'australian',
 'author',
 'autism',
 'auto',
 'aveng',
 'averag',
 'avoid',
 'await',
 'awaken',
 'award',
 'award win',
 'away',
 'away hi',
 'awkward',
 'awri',
 'awry',
 'ax',
 'babe',
 'babi',
 'baby',
 'bachelor',
 'backdrop',
 'background',
 'bad',
 'bad guy',
 'bag',
 'bahama',
 'bail',
 'balanc',
 'ball',
 'ballet',
 'band',
 'band togeth',
 'bandit',
 'banish',
 'bank',
 'banker',
 'bankrobb',
 'bankrobberi',
 'bar',
 'bare',
 'bargain',
 'barn',
 'barney',
 'baron',
 'barri',
 'barrylevinson',
 'bas',
 'base',
 'base novel',
 'base true',
 'base true stori',
 'base true story',
 'basebal',
 'basedoncomicbook',
 'basedoncomicbook superhuman',
 'basedongraphicnovel',
 'basedonnovel',
 'basedonplay',
 'basedonstagemus',
 'basedontrueev',
 'basedontruestori',
 'basedontvseri',
 'basedonvideogam',
 'basedonyoungadultnovel',
 'basement',
 'basketbal',
 'batman',
 'battl',
 'battle',
 'battlefield',
 'bay',
 'beach',
 'bear',
 'beast',
 'beat',
 'beauti',
 'beauti girl',
 'beautiful',
 'beautifulwoman',
 'beauty',
 'becam',
 'becaus',
 'becom',
 'becom hi',
 'becom increasingli',
 'becom involv',
 'becom obsess',
 'becom target',
 'becominganadult',
 'bed',
 'bedroom',
 'beer',
 'befor',
 'befor hi',
 'befor late',
 'befor long',
 'befriend',
 'began',
 'begin',
 'begin fall',
 'begin hi',
 'begin unravel',
 'begins',
 'behavior',
 'belief',
 'believ',
 'believ hi',
 'bell',
 'bella',
 'belong',
 'belov',
 'ben',
 'benaffleck',
 'bend',
 'beneath',
 'benefit',
 'benfost',
 'beniciodeltoro',
 'benjamin',
 'benjaminbratt',
 'benkingsley',
 'bennett',
 'benstil',
 'bent',
 'berlin',
 'best',
 'best friend',
 'best friends',
 'best sel',
 'bestfriend',
 'bet',
 'beth',
 'betray',
 'bettemidl',
 'better',
 'better life',
 'betti',
 'beverli',
 'bibl',
 'big',
 'big citi',
 'big screen',
 'bigger',
 'biggest',
 'biker',
 'bikini',
 'billhad',
 'billi',
 'billionair',
 'billmurray',
 'billnighi',
 'billpaxton',
 'billpullman',
 'billybobthornton',
 'billycrudup',
 'billycryst',
 'biographi',
 'biographi basedontruestori',
 'biographi sport',
 'biolog',
 'bird',
 'birth',
 'birthday',
 'bisexu',
 'bishop',
 'bit',
 'bite',
 'bitter',
 'bizarr',
 'black',
 'blackmag',
 'blackmail',
 'blackpeopl',
 'blade',
 'blame',
 'blend',
 'blind',
 'bliss',
 'block',
 'blond',
 'blood',
 'bloodi',
 'bloodsplatt',
 'bloodthirsti',
 'blow',
 'blue',
 'board',
 'board school',
 'boardingschool',
 'boat',
 'bob',
 'bobbi',
 'bobbyfarrelli',
 'bobhoskin',
 'bodi',
 'body',
 'bodyguard',
 'bold',
 'bollywood',
 'bomb',
 'bond',
 'bone',
 'book',
 'border',
 'bore',
 'boredom',
 'born',
 'boss',
 'boston',
 'botch',
 'bound',
 'boundari',
 'bounti',
 'bounti hunter',
 'bountyhunt',
 'box',
 'boxer',
 'boy',
 'boyfriend',
 'boys',
 'bradleycoop',
 'bradpitt',
 'brain',
 'brand',
 'brave',
 'braveri',
 'brazil',
 'brazilian',
 'break',
 'break free',
 'breakdown',
 'breath',
 'breed',
 'brendanfras',
 'brendangleeson',
 'brettratn',
 'brian',
 'briandepalma',
 'bride',
 'bridesmaid',
 'bridg',
 'brief',
 'brilliant',
 'bring',
 'bring hi',
 'brink',
 'britain',
 'british',
 'britishsecretservic',
 'broadcast',
 'broadway',
 'broke',
 'broken',
 'broker',
 'brook',
 'brooklyn',
 'brothel',
 'brother',
 'brotherbrotherrelationship',
 'brothers',
 'brothersisterrelationship',
 'brought',
 'brown',
 'bruce',
 'brucewilli',
 'brutal',
 'brutal murder',
 'bu',
 'buck',
 'bud',
 'buddi',
 'buddycomedi',
 'budget',
 'build',
 'building',
 'built',
 'bullet',
 'bulli',
 'bumbl',
 'burglar',
 'buri',
 'burn',
 'bush',
 'busi',
 'business',
 'businessman',
 'bust',
 'butler',
 'buy',
 'cabin',
 'caesar',
 'cage',
 'cairo',
 'cal',
 'california',
 'calvin',
 'camcord',
 'came',
 'camera',
 'cameraman',
 'camerondiaz',
 'camp',
 'campaign',
 'campu',
 'canada',
 'canadian',
 'cancer',
 'candid',
 'canin',
 'cannib',
 'capabl',
 'capit',
 'capt',
 'captain',
 'captiv',
 'captur',
 'car',
 'car accident',
 'car crash',
 'caraccid',
 'carchas',
 'carcrash',
 'card',
 'care',
 'career',
 'carefre',
 'caretak',
 'caribbean',
 'carjourney',
 'carl',
 'carlagugino',
 'carmen',
 'carol',
 'carolina',
 'carrac',
 'carri',
 'carri hi',
 'carrie',
 'carrie annemoss',
 'cartel',
 'carter',
 'caryelw',
 'case',
 'caseyaffleck',
 'cash',
 'casino',
 'cast',
 'castl',
 'cat',
 'cat mous',
 'cataclysm',
 'catastroph',
 'catch',
 'cateblanchett',
 'catherinekeen',
 'catherinezeta',
 'catherinezeta jon',
 'cathol',
 'catholic',
 'caught',
 'caus',
 'cavalri',
 'cave',
 'celebr',
 'cellphon',
 'cemeteri',
 'center',
 'central',
 'centuri',
 'centuries',
 'century',
 'certain',
 'chain',
 'chainsaw',
 'challeng',
 'champion',
 'championship',
 'chanc',
 'chance',
 'chang',
 'chang hi',
 'chang hi life',
 'chang live',
 'channingtatum',
 'chao',
 'chaos',
 'chapter',
 'charact',
 'character',
 'characters',
 'charg',
 'charismat',
 'charl',
 'charli',
 'charlie',
 'charliesheen',
 'charlizetheron',
 'charm',
 'chart',
 'chase',
 'chauffeur',
 'cheat',
 'check',
 'cheerlead',
 'chef',
 'chemic',
 'chicago',
 'chicken',
 'chief',
 'child',
 'childabus',
 'childhood',
 'childhood friend',
 'children',
 'chill',
 'china',
 'chines',
 'chip',
 'chocol',
 'choic',
 'choos',
 'chosen',
 'chri',
 'chriscolumbu',
 'chrisevan',
 'chrishemsworth',
 'chrispin',
 'chrisrock',
 'christ',
 'christian',
 'christianbal',
 'christianslat',
 'christinaappleg',
 'christinaricci',
 'christma',
 'christma eve',
 'christmas',
 'christmasparti',
 'christoph',
 'christopherlloyd',
 'christophernolan',
 'christopherplumm',
 'christopherwalken',
 'christophwaltz',
 'chronicl',
 'chuck',
 'church',
 'cia',
 'cia agent',
 'cia oper',
 'cigarettesmok',
 'cillianmurphi',
 'cinema',
 'circl',
 'circu',
 'circuit',
 'circumst',
 'citi',
 'citizen',
 'city',
 'civil',
 'civil war',
 'civilian',
 'civilwar',
 'claim',
 'clair',
 'clairedan',
 'clan',
 'clark',
 'clash',
 'class',
 'classic',
 'classmat',
 'classroom',
 'claudevandamm',
 'clay',
 'clean',
 'clear',
 'clerk',
 'client',
 'climat',
 'climb',
 'clinteastwood',
 'cliveowen',
 'clock',
 'clone',
 'close',
 'close friend',
 'closer',
 'clown',
 'club',
 'clue',
 'clutch',
 'cn',
 'coach',
 'coast',
 'cocain',
 'code',
 'coffin',
 'cohen',
 'col',
 'cold',
 'coldwar',
 'cole',
 'colin',
 'colinfarrel',
 'colinfirth',
 'collaps',
 'colleagu',
 'collect',
 'collector',
 'colleg',
 'colleg student',
 'college',
 'collid',
 'collis',
 'colonel',
 'coloni',
 'color',
 'colorado',
 'coma',
 'combat',
 'combin',
 'come',
 'come age',
 'come face',
 'come face face',
 'come hi',
 'come home',
 'come life',
 'come term',
 'come togeth',
 'come true',
 'comeback',
 'comed',
 'comedi',
 'comedi action',
 'comedi adventur',
 'comedi anim',
 'comedi crime',
 'comedi crime drama',
 'comedi crime thriller',
 'comedi documentari',
 'comedi drama',
 'comedi drama famili',
 'comedi drama fantasi',
 'comedi drama histori',
 'comedi drama independentfilm',
 'comedi drama music',
 'comedi drama romanc',
 'comedi drama suicid',
 'comedi drama thriller',
 'comedi duringcreditssting',
 'comedi famili',
 'comedi famili adventur',
 'comedi famili fantasi',
 'comedi famili holiday',
 'comedi famili romanc',
 'comedi famili sciencefict',
 'comedi fantasi',
 'comedi horror',
 'comedi independentfilm',
 'comedi music',
 'comedi music romanc',
 'comedi romanc',
 'comedi romanc drama',
 'comedi romanc independentfilm',
 'comedi sciencefict',
 'comedi sex',
 'comedi thriller',
 'comedi thriller crime',
 'comedi western',
 'comedian',
 'comedy',
 'comfort',
 'comic',
 'coming',
 'coming ag',
 'comingofag',
 'comingout',
 'command',
 'commando',
 'commerci',
 'commit',
 'common',
 'commun',
 'community',
 'compani',
 'companion',
 'company',
 'compet',
 'competit',
 'competition',
 'complet',
 'complex',
 'complic',
 'compos',
 'comput',
 'conan',
 'concern',
 'concert',
 'condit',
 'confess',
 'confid',
 'conflict',
 'confront',
 ...]

In [43]:
from sklearn.metrics.pairwise import cosine_similarity

In [44]:
similarity=cosine_similarity(vctrs)

In [54]:
pickle.dump(similarity,open('similarity.pkl','wb'))

In [45]:
similarity.shape

(4800, 4800)

In [46]:
sorted(enumerate(list(similarity[0])),reverse=True,key=lambda x:x[1])[1:6]

[(1191, 0.20906586997101786),
 (3723, 0.20248031239729752),
 (47, 0.1992128414193754),
 (2403, 0.1958154288453348),
 (778, 0.1926153444844409)]

In [47]:
def recommand(movie):
    movie_index=new_df[new_df['original_title']==movie].index[0]
    dis=similarity[movie_index]
    movie_list=sorted(enumerate(list(dis)),reverse=True,key=lambda x:x[1])[1:6]
    
    for i in movie_list:
        print(new_df.iloc[i[0]]['original_title'])

In [48]:
recommand('Spectre')

Skyfall
Quantum of Solace
Never Say Never Again
Restless
Thunderball

In [49]:
import pickle

In [52]:
pickle.dump(recommand,open('recommand.pkl','wb'))